//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.CompraDetalle = new HashSet<CompraDetalle>();
        }
    
        public int IdCompra { get; set; }
        public int IdEmpresa { get; set; }
        public int IdEntidad { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Serie { get; set; }
        public string Correlativo { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public decimal Importe { get; set; }
        public decimal IGV { get; set; }
        public decimal Total { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraDetalle> CompraDetalle { get; set; }
    }
}
