//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoContenedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoContenedor()
        {
            this.ContratoPeso = new HashSet<ContratoPeso>();
            this.ContratoPrecinto = new HashSet<ContratoPrecinto>();
            this.LlenadoContenedor = new HashSet<LlenadoContenedor>();
            this.ContratoFoto = new HashSet<ContratoFoto>();
        }
    
        public int IdContratoContenedor { get; set; }
        public int IdContrato { get; set; }
        public string NroContenedor { get; set; }
        public int Payload { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPeso> ContratoPeso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPrecinto> ContratoPrecinto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LlenadoContenedor> LlenadoContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoFoto> ContratoFoto { get; set; }
    }
}
