//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoContenedor = new HashSet<ContratoContenedor>();
            this.ContratoLote = new HashSet<ContratoLote>();
            this.ContratoPeso = new HashSet<ContratoPeso>();
            this.ContratoPrecinto = new HashSet<ContratoPrecinto>();
            this.LlenadoContenedor = new HashSet<LlenadoContenedor>();
            this.ContratoFoto = new HashSet<ContratoFoto>();
        }
    
        public int IdContrato { get; set; }
        public int IdEmpresa { get; set; }
        public string NroContrato { get; set; }
        public string NroContratoLote { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string LugarCarga { get; set; }
        public System.DateTime FechaDescarga { get; set; }
        public string LugarDescarga { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoContenedor> ContratoContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoLote> ContratoLote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPeso> ContratoPeso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoPrecinto> ContratoPrecinto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LlenadoContenedor> LlenadoContenedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoFoto> ContratoFoto { get; set; }
    }
}
