//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoLote
    {
        public int IdContratoLote { get; set; }
        public int IdContrato { get; set; }
        public int IdLote { get; set; }
        public int Cantidad { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Lote Lote { get; set; }
    }
}
