//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoFoto
    {
        public int IdContratoFoto { get; set; }
        public Nullable<int> IdContrato { get; set; }
        public Nullable<int> IdContratoContenedor { get; set; }
        public string Foto { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual ContratoContenedor ContratoContenedor { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
