//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsolidadosEntities : DbContext
    {
        public ConsolidadosEntities()
            : base("name=ConsolidadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacen> Almacen { get; set; }
        public virtual DbSet<ClasificacionTipoDocumento> ClasificacionTipoDocumento { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<CompraDetalle> CompraDetalle { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<ContratoContenedor> ContratoContenedor { get; set; }
        public virtual DbSet<ContratoLote> ContratoLote { get; set; }
        public virtual DbSet<ContratoPeso> ContratoPeso { get; set; }
        public virtual DbSet<ContratoPrecinto> ContratoPrecinto { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Entidad> Entidad { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<LlenadoContenedor> LlenadoContenedor { get; set; }
        public virtual DbSet<Lote> Lote { get; set; }
        public virtual DbSet<Movimiento> Movimiento { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoMovimiento> TipoMovimiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<ContratoFoto> ContratoFoto { get; set; }
    }
}
