//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consolidados.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int IdMovimiento { get; set; }
        public int IdTipoMovimiento { get; set; }
        public int IdEmpresa { get; set; }
        public int IdLote { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public int StockInicial { get; set; }
        public int Ingreso { get; set; }
        public int Salida { get; set; }
        public Nullable<int> StockActual { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Lote Lote { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
